import Head from "next/head";
import axios from "axios";
import GridList from "../components/GridList";

export default function Home({ events, categories }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-4 md:px-8 max-w-7xl mx-auto">
        <GridList events={events} />
      </main>
    </div>
  );
}

export const getStaticProps = async () => {
  const eventData = await axios
    .get(
      `https://eonet.gsfc.nasa.gov/api/v2.1/events?api_key=${process.env.NASA_API_KEY}&&limit=30`
    )
    .then((response) => {
      return response.data.events;
    });

  const categoryData = await axios
    .get(
      `https://eonet.gsfc.nasa.gov/api/v2.1/categories?api_key=${process.env.NASA_API_KEY}`
    )
    .then((response) => {
      return response.data.categories;
    });

  if (eventData && categoryData) {
    return {
      props: {
        events: eventData,
        categories: categoryData,
      },
    };
  }
  if (!eventData && !categoryData) {
    return {
      props: {
        events: [],
        categories: [],
      },
    };
  }
  if (!eventData && categoryData) {
    return {
      props: {
        events: [],
        categories: categoryData,
      },
    };
  }

  if (eventData && !categoryData) {
    return {
      props: {
        events: eventData,
        categories: [],
      },
    };
  }
};
